apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: sampleapp
  name: sampleapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: sampleapp
  sessionAffinity: None
  type: ClusterIP
