apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sampleapp-ingress
  annotations:
    kubernetes.io/ingress.class: default
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - sampleapp-amp.apps-test.aws.e1.nwie.net
    secretName: sample-app-ssl-cert
  rules:
  - host: sampleapp-amp.apps-test.aws.e1.nwie.net
    http:
      paths:
      - backend:
          # Reference your Service by name
          serviceName: sampleapp  
          # Reference your Service Port by either name or number
          # servicePort: http
          servicePort: 8080
