apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sampleapp-ssl
spec:
  secretName: sampleapp-ssl
  issuerRef:
    name: nwie
    kind: ClusterIssuer
  commonName: sampleapp-amp.apps-test.aws.e1.nwie.net
  dnsNames:
  - sampapp-alias.nwie.net
